pipeline {
    agent any

    stages {

        stage('Delete Cluster') {
            steps {
              // Ignore failure if the cluster does not exist
              catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
              // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
                withCredentials([[
                  $class: 'AmazonWebServicesCredentialsBinding',
                  credentialsId: "aws_credentials_id",
                  accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                  secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                  ]]) {
                  sh "eksctl delete cluster --name eks-cluster --region us-east-1"
                }
              }  
            }
        }
    }
}