apiVersion: apps/v1
kind: Deployment
metadate:
  name: survey-app-deploy
  namespace: python-app
  labels:
    app: survey-app
spec:
  selector:
    matchLabels:
       app: survey-app
  replicas: 2
  template:
    metadata:
     labels:
       app: survey-app
    spec:
     containers:
     - name: python-container
       image: mohamedabdelaziz10/survey-app-img:latest
       ports:
       - containerPort: 8000
